/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.bean.BeanVenda;
import model.dao.DaoVenda;

/**
 *
 * @author Junior Guilherme
 */
public class JIFVendas extends javax.swing.JInternalFrame {
    DaoVenda dao = new DaoVenda();
    /**
     * Creates new form JIFVendas
     */
    public JIFVendas() {
        initComponents();
        dao.readVendaJIF(jtVenda);
    }
    public void limpaCampos(){
        txtBusca.setText("");
        txtID.setText("");
        txtQTD.setText("");
        txtValor.setText("");
    }
    public boolean isValidDate(String date, String format) {         
	SimpleDateFormat dateFormat = new SimpleDateFormat(format);     
	dateFormat.setLenient(false);                                   
	try {                                                           
		dateFormat.parse(date);                                     
		return true;                                                
	} catch (ParseException e) {  
                JOptionPane.showMessageDialog(null, "Data invalida.");
		return false;                                               
        }
    }

    public boolean isValidNumbers(int qtd, double valor) {
        if (qtd >= 0 && valor >= 0) {
            return true;
        }
        else{
            JOptionPane.showMessageDialog(null, "Não informe numeros negativos nos campos 'Quantidade' e 'Valor'.");
            return false;
        }
    }

    public String dataJava(String data) {
        String ano = data.substring(0, 4);
        String mes = data.substring(4, 8);
        String dia = data.substring(8, 10);
        data = dia + mes + ano;
        return data;
    }
    public String dataSql(String data){
        String ano = data.substring(6, 10);
        String mes = data.substring(2, 6);
        String dia = data.substring(0, 2);
        data = ano+mes+dia;
        return data;
    }
    public void confirmaUpdate(BeanVenda v){
        v.setQtd(Integer.parseInt(txtQTD.getText()));
        v.setValor(Double.parseDouble(txtValor.getText()));
        v.setId(Integer.parseInt(txtID.getText()));
        v.setNomeProduto(jtVenda.getValueAt(jtVenda.getSelectedRow(), 1).toString());
        int reply = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente atualizar esta venda com estas informações?\n ID Venda: " + v.getId() + " \nProduto: " + v.getNomeProduto() + "\nQuantidade: " + String.valueOf(v.getQtd()) + "\nValor: " + String.valueOf(v.getValor()) + "\nData: " + v.getDataSql().toString());
            if (reply == JOptionPane.YES_OPTION) {
                dao.update(v);
                dao.readVendaJIF(jtVenda);;
                limpaCampos();
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtVenda = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQTD = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jfData = new javax.swing.JFormattedTextField();
        cbHoje = new javax.swing.JCheckBox();

        setClosable(true);

        jtVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Produto", "Quantidade", "Valor", "Data", "Custo", "Lucro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVenda.setShowHorizontalLines(false);
        jtVenda.setShowVerticalLines(false);
        jtVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtVenda);
        if (jtVenda.getColumnModel().getColumnCount() > 0) {
            jtVenda.getColumnModel().getColumn(0).setPreferredWidth(5);
            jtVenda.getColumnModel().getColumn(1).setPreferredWidth(120);
            jtVenda.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo da Venda");

        txtID.setEditable(false);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade");

        jLabel3.setText("Valor");

        jLabel4.setText("Data");

        cbHoje.setText("Hoje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtQTD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jfData, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbHoje)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHoje))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnRemover)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(txtBusca))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVendaMouseClicked
        // TODO add your handling code here:
        if(jtVenda.getSelectedRow()!= -1){
            txtQTD.setText(jtVenda.getValueAt(jtVenda.getSelectedRow(), 2).toString());
            txtValor.setText(jtVenda.getValueAt(jtVenda.getSelectedRow(), 4).toString());
            jfData.setText(dataJava(jtVenda.getValueAt(jtVenda.getSelectedRow(), 3).toString()));
            txtID.setText(jtVenda.getValueAt(jtVenda.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_jtVendaMouseClicked

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        BeanVenda v;
        v=dao.readForId(Integer.parseInt(txtID.getText()));
        String data = jtVenda.getValueAt(jtVenda.getSelectedRow(), 3).toString();
        v.setData(dao.dataJava(data));
        int reply = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente remover esta venda? \nProduto: "+v.getNomeProduto()+"\nQuantidade: "+String.valueOf(v.getQtd())+"\nValor:"+String.valueOf(v.getValor())+"\nData: "+v.getData().toString());
        if(reply==JOptionPane.YES_OPTION){
            dao.remove(Integer.parseInt(txtID.getText()));
            dao.readVendaJIF(jtVenda);
            limpaCampos();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        BeanVenda v = new BeanVenda();
        DaoVenda dao = new DaoVenda();
        Date dataA;
        
        if(cbHoje.isSelected()){
            dataA = new Date(System.currentTimeMillis());
            v.setDataSql(dataA);
            if (isValidNumbers(Integer.parseInt(txtQTD.getText()), Double.parseDouble(txtValor.getText()))) {
                confirmaUpdate(v);
            }
        } else {
            if (isValidDate(jfData.getText(), "dd-MM-yyyy") && isValidNumbers(Integer.parseInt(txtQTD.getText()), Double.parseDouble(txtValor.getText()))) {
                dataA = Date.valueOf(dataSql(jfData.getText()));
                v.setDataSql(dataA);
                confirmaUpdate(v);
            }
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DaoVenda dao = new DaoVenda();
        dao.readJtableRS2(txtBusca.getText(), jtVenda);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JCheckBox cbHoje;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jfData;
    private javax.swing.JTable jtVenda;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtQTD;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
